/**
 * Internal Events Enum
 * (used for internal backend events handling using NestJs EventEmitter)
 */

export enum InternalEventsEnum {
  AI_GENERATE_PROPOSITION_ARGUMENTS = "AI_GENERATE_PROPOSITION_ARGUMENTS",

  DEBATE_INITIALIZE_CONTEXT = "DEBATE_INITIALIZE_CONTEXT",

  USER_CHECK_MISSIONS_FOR_USER = "USER_CHECK_MISSIONS_FOR_USER",

  VOTE_NEW_VOTE = "VOTE_NEW_VOTE",

  DECISION_NEW_DECISION_TO_BE_FEATURED = "DECISION_NEW_DECISION_TO_BE_FEATURED",
  DECISION_NEW_FEATURED_DECISION = "DECISION_NEW_FEATURED_DECISION",

  TERRITORY_FEATURED_DECITIONS_TRIGGER_UPDATE = "TERRITORY_FEATURED_DECITIONS_TRIGGER_UPDATE"
}
