export enum SubjectTheme {
  ECONOMY = "ECONOMY",
  ENVIRONMENT = "ENVIRONMENT",
  SOLIDARITY_HEALTH = "SOLIDARITY_HEALTH",
  SECURITY_JUSTICE = "SECURITY_JUSTICE",
  DEFENSE = "DEFENSE",
  INTERNATIONAL = "INTERNATIONAL",
  CULTURE_SPORT = "CULTURE_SPORT",
  HOUSING = "HOUSING",
  ENERGY = "ENERGY",
  TRANSPORT = "TRANSPORT",
  WORK = "WORK",
  EDUCATION = "EDUCATION",
  PUBLIC_CIVIL_SERVICES = "PUBLIC_CIVIL_SERVICES",
  OTHER = "OTHER"
}
